---
- name: create group prometheus
  group:
    name: prometheus
    state: present

- name: Add user prometheus to group prometheus
  user:
    name: prometheus
    shell: /bin/bash
    groups: prometheus
    append: yes

- name: timezone
  timezone:
    name: Asia/Tokyo

- name: locale
  command: localectl set-locale LANG=ja_JP.UTF-8
  when: ansible_env.LANG != "ja_JP.UTF-8"
