---
global:
 scrape_interval:     15s
 evaluation_interval: 15s 
 
alerting:
 alertmanagers:
 - static_configs:
   - targets:
     - 'localhost:9093' 
 
rule_files:
 - "alert_rules.yml"
 
scrape_configs:
 - job_name: 'node'
   static_configs:
     - targets:
       - '192.168.33.21:9100'
 
 - job_name: 'nginx'
   static_configs:
     - targets:
       - '192.168.33.21'
 
 - job_name: 'http_200'
   metrics_path: /probe
   params:
     module: ['http_2xx']
   static_configs:
     - targets:
       - 'http://192.168.33.21'
   relabel_configs:
     - source_labels: [__address__]
       target_label: __param_target
     - source_labels: [__param_target]
       target_label: instance
     - target_label: __address__
       replacement: localhost:9115
