---
- name: check exists node_exporter
  stat:
    path: /usr/lib/systemd/system/node_exporter.service
  register: node_exporter

- name: Install node_exporter
  unarchive:
    src: https://github.com/prometheus/node_exporter/releases/download/v1.0.1/node_exporter-1.0.1.linux-amd64.tar.gz
    dest: /usr/local/src/
    remote_src: yes
  when: node_exporter.stat.exists == false

- name: Rename Directory
  command: mv /usr/local/src/node_exporter-1.0.1.linux-amd64 /usr/local/src/node_exporter
  when: node_exporter.stat.exists == false

- name: copy item to /usr/local/bin
  copy:
    src: /usr/local/src/node_exporter/node_exporter
    dest: /usr/local/bin/
    mode: "0755"
    remote_src: yes

- name: add node_exporter.service to systemd
  copy:
    src: node_exporter.service
    dest: /usr/lib/systemd/system/

- name: enable and start node_exporter
  systemd:
    name: node_exporter
    state: restarted
    daemon_reload: yes
    enabled: yes
